### PR TITLE
feat(external): pack node_modules when esbuild-node-externals is configured

### PR DESCRIPTION
**Pull request by vamche**
Closes https://github.com/floydspace/serverless-esbuild/issues/136

### CODE REVIEW

**Comment by vamche** [comment]
@floydspace Could you please review this?

**Review by floydspace — APPROVED** [review]
Hi @vamche , looks good to me, the only thing, it would be good to add some comment about this feature in the readme.

**Comment by vamche** [comment]
@floydspace update the readme. Thank you!

**Comment by floydspace** [comment]
@vamche, Thank you for contribution 👍 merged it

**Pull request merged**
