### PR TITLE
chore: linting

### PR DESCRIPTION
**Pull request by webdeveric**
- updated dev dependencies
- updated linting rules
- fixes for :point_up: rules

### CODE REVIEW

**Comment by floydspace** [comment]
I wanna reuse the ruleset I created a while ago for all my projects https://github.com/floydspace/linters
which is basically a fork from https://github.com/Tinkoff/linters with some additions.

Let me raise the PR. Thank you for spending time on this though.

**Comment by webdeveric** [comment]
@floydspace Should I close this one? There are some fixes in here that I think should be merged.

**Comment by floydspace** [comment]
Let me continue in your branch. if you don't mind

**Review by floydspace — APPROVED** [review]
@webdeveric done, good if you quickly check the new changes

**Pull request merged**
