### PR TITLE
Allow esbuild 0.19

### PR DESCRIPTION
**Pull request by ZachLeviPixel**
Following up on https://github.com/floydspace/serverless-esbuild/pull/473 by @fm-sz, updated esbuild to 0.19.3.
Since the initial pull request started removing the incremental parameters, I followed suit to remove the disableIncremental option as well, which caused tests to fail. Also solved conflicts between the pull request and master.

### CODE REVIEW

**Comment by floydspace** [comment]
hey @ZachLeviPixel, thank you for picking it up, I ran the tests for your branch, but unfortunately, tests failed in CI, could you please have a look?

**Comment by Runescrye** [comment]
I will take another look at it at the next opportunity.

**Comment by ZachLeviPixel** [comment]
Hum. I'll take a look at it tomorrow, thanks.

**Comment by ZachLeviPixel** [comment]
Updated the pull request, reverted package.json and the lockfile to master versions and reimported esbuild 19. Checked that the tests pass on the fork.

**Review by floydspace — APPROVED** [review]
Thank you @ZachLeviPixel. Looks fine to me, I'm ready to merge

**Comment by floydspace** [comment]
@all-contributors please add @ZachLeviPixel and @fm-sz for new code as a matter of appreciation

**Comment by floydspace** [comment]
@all-contributors please don't forget to add @fm-sz for new code as well

**Pull request merged**
