### PR TITLE
fix: make sure all the dependencies are checked when flattening the d…

### PR DESCRIPTION
**Pull request by danionescu**
…ependencies tree (#103)

This needs more testing. For example, my own project, I am getting the error `Error: Cannot find module 'source-map-support/register'`, which I have seen before my fix.

### CODE REVIEW

**Comment by samchungy** [comment]
Would a package version affect the dependencies we need?

Eg. If one package had

X@0.1 as a dep

And then another had

X@0.2 as a dep

**Comment by danionescu** [comment]
I am not sure how that would work with the current code. I pushed another commit that saves the dependencies for each version.

**Comment by samchungy** [comment]
> I am not sure how that would work with the current code. I pushed another commit that saves the dependencies for each version.

Neither tbh, was just curious if you knew aha 😅

**Comment by danionescu** [comment]
Lol, I took a bottom up approach to fixing this, assuming the rest of the is correct, so I just tried to add the pieces that were missing in this place. I would need to study the rest of the code to make sure it is correct, but I don't think that I will have the time soon.

**Review by samchungy — APPROVED** [review]
This looks good to me. Thanks for the contribution @danionescu!

I answered my above question with this helpful medium article. https://medium.com/learnwithrahul/understanding-npm-dependency-resolution-84a24180901b 

I did give this a run locally and it lgtm. It brings across the correct dependencies.

**Comment by samchungy** [comment]
@olup @floydspace want to give this a final look?

**Review by floydspace — APPROVED** [review]

**Comment by floydspace** [comment]
I pushed the button, thank you @danionescu @samchungy

**Pull request merged**
