### PR TITLE
feat: set esbuild as a peer depedency

### PR DESCRIPTION
**Pull request by samchungy**
`esbuild` is now a peer dependency. Please install `esbuild` as a dev dependency for your projects.

### CODE REVIEW

**Comment by samchungy** [comment]
From our convo in https://github.com/floydspace/serverless-esbuild/pull/238

**Comment by floydspace** [comment]
@samchungy oh, I guess this commit will update the package to v2, which I wouldn't feel like doing.
It should be really something major to update to the v2, IMO.

**Comment by floydspace** [comment]
it'd be nice to fix readme as well.

**Comment by samchungy** [comment]
> @samchungy oh, I guess this commit will update the package to v2, which I wouldn't feel like doing. It should be really something major to update to the v2, IMO.

yeah fair enough. I guess we can just mention it.

**Review by floydspace — APPROVED** [review]
@samchungy  thank you, merging it

**Pull request merged**
